package com.mvbr.retailstore.checkout.domain.model;

public enum SagaStep {
    STARTED,
    INVENTORY_RESERVE_PENDING,
    PAYMENT_AUTHORIZE_PENDING,
    ORDER_COMPLETE_PENDING,
    COMPENSATE_INVENTORY_RELEASE_PENDING,
    COMPENSATE_ORDER_CANCEL_PENDING,
    WAITING_COMPENSATIONS,
    DONE
}
